Testing: workaround TypeScript compiler limitation
It appears that

    assert.equal(lastArgs?.type, 'dirty', 'setDirty/isDirty');

causes error

    error TS2339: Property 'type' does not exist on type 'never'.

I think this is actually a bug in tsc:

    https://github.com/Microsoft/TypeScript/issues/11498

So this should be considered a workaround only. Alternative solution
would be to annotate this line as @ts-ignore.